### ISSUE TITLE
Please clarify licence for this project

### ISSUE THREAD

**Issue by rasq** [davidnajar/EzInstaller#1]
Hi, 
i see that [EzInstaller](https://github.com/davidnajar/EzInstaller) is one of your project and this is in minority without any licence clarification.

**Comment by davidnajar** [comment]
Hi,
I will add a license file in the next minutes. 
Is true that i did this project long time ago and has not been mantained. I might be update to latest framework at least.

**Comment by rasq** [comment]
Thx. That's great.
